name: nist_tes
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  dio: ^5.4.2+1
  shared_preferences: ^2.2.3
  provider: ^6.1.2
  go_router: ^13.2.4
  persistent_bottom_nav_bar_v2: ^5.2.3
  awesome_bottom_bar: ^1.2.4
  flex_color_scheme: ^7.3.1
  table_calendar: ^3.1.2
  intl: ^0.19.0
  flutter_svg: ^2.0.10+1
  flutter_vector_icons: ^2.0.0
  logger: ^2.4.0
  json_annotation: ^4.9.0
  hive_flutter: ^1.1.0
  shimmer: ^3.0.0
  flutter_cache_manager: ^3.3.3
  connectivity_plus: ^6.0.4
  pull_to_refresh_new: ^2.0.5
  firebase_core: ^2.24.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.11
  hive_generator: ^2.0.1
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/fonts/
    - assets/svg/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-Black.ttf
          weight: 900
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Montserrat-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Montserrat-Light.ttf
          weight: 300
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-Thin.ttf
          weight: 100
